# Sudhi Library
@startuml

object Bookid 
object BookName
object Author

object thumbnailurl
object price
object status

object RequestrejectorRequestedorWaitingstored  
object existing
object borrowed
object locationunknown

object userid
object name
object rank
object admin
object normal


object Book



object BookListPage
object BookRegistrationPage
object BookRequestPage
object BookLendingPage
object BookReturnPage






Book "1" -- "1" Bookid

Book "1" -- "1" BookName
Book "1" -- "1" Author

Book "1" -- "1" thumbnailurl
Book "1" *-- "*" price
Book "1" *-- "*" status

status  "1" *-- "*" RequestrejectorRequestedorWaitingstored 
status  "1" *-- "*" existing
status  "1" *-- "*" borrowed
status  "1" *-- "*" locationunknown

userid "1" -- "1" name
userid "1" -- "1" rank
rank "1" -- "1" admin
rank "1" -- "1" normal
 




















@enduml
