@startuml
title Robustness(List Books)
actor User
boundary WebPage

package SushiLibrary{
    boundary ChoosePage
    boundary BookListPage

    control "Listup Books" as ListB
    control "Check the User" as CheckUser

    entity Book
    entity UserInfo

}

User --> WebPage
WebPage --> ChoosePage
WebPage <-- BookListPage

ChoosePage --> CheckUser

CheckUser --> ListB : If check is ok
CheckUser -- UserInfo

ListB -- Book
ListB -up-> BookListPage

@enduml

@startuml
title Robustness(Register Books)
actor User
boundary WebPage

package SushiLibrary{
    boundary ChoosePage
    
    boundary BookRegistrationPage

    control "Register Book" as RegB
    control "Check the User" as CheckUser

    entity Book
    entity UserInfo

}

User --> WebPage
WebPage --> ChoosePage
WebPage <-- BookRegistrationPage

ChoosePage --> CheckUser
CheckUser -- UserInfo
CheckUser --> RegB : If check is ok
RegB -- Book
RegB -up-> BookRegistrationPage

@enduml