@startuml

actor User


package SushiLibrary{
    
    "Showing Boook List" as (ShowBook)
    "Register User info" as (RegUser)

    "Register Book" as (RegB)
    "Lending Books" as (LendB)
    "Returnig Books" as (RetB)
    "Request Books" as (ReqB) 
    "Approve/Reject Request" as (AprvRejReq)

    "Login/Logout" as (Loginout)
    "Display Book info" as (Book)
    "Display User info" as (Userif)
    "Display Book status" as (Books)
}




Loginout --> ShowBook
Loginout --> RegB
Loginout --> LendB
Loginout --> RetB
Loginout --> ReqB
Loginout --> AprvRejReq
Loginout --> RegUser
User --> Loginout

RegUser --> Userif
RegB --> Book
ShowBook --> Book

ReqB --> Books
AprvRejReq --> Books
LendB --> Books
RetB --> Books













@enduml